/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiSimStreamRouteImport } from './routes/api/sim/stream'
import { Route as ApiSimOrderRouteImport } from './routes/api/sim/order'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiEventsWorkflowRouteImport } from './routes/api/events/workflow'
import { Route as ApiEventsTradingRouteImport } from './routes/api/events/trading'
import { Route as ApiEventsTradesRouteImport } from './routes/api/events/trades'
import { Route as ApiEventsPositionsRouteImport } from './routes/api/events/positions'
import { Route as ApiEventsConversationsRouteImport } from './routes/api/events/conversations'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimStreamRoute = ApiSimStreamRouteImport.update({
  id: '/api/sim/stream',
  path: '/api/sim/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimOrderRoute = ApiSimOrderRouteImport.update({
  id: '/api/sim/order',
  path: '/api/sim/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsWorkflowRoute = ApiEventsWorkflowRouteImport.update({
  id: '/api/events/workflow',
  path: '/api/events/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsTradingRoute = ApiEventsTradingRouteImport.update({
  id: '/api/events/trading',
  path: '/api/events/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsTradesRoute = ApiEventsTradesRouteImport.update({
  id: '/api/events/trades',
  path: '/api/events/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsPositionsRoute = ApiEventsPositionsRouteImport.update({
  id: '/api/events/positions',
  path: '/api/events/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsConversationsRoute = ApiEventsConversationsRouteImport.update({
  id: '/api/events/conversations',
  path: '/api/events/conversations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/simulator': typeof SimulatorRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events/conversations': typeof ApiEventsConversationsRoute
  '/api/events/positions': typeof ApiEventsPositionsRoute
  '/api/events/trades': typeof ApiEventsTradesRoute
  '/api/events/trading': typeof ApiEventsTradingRoute
  '/api/events/workflow': typeof ApiEventsWorkflowRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sim/order': typeof ApiSimOrderRoute
  '/api/sim/stream': typeof ApiSimStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/simulator': typeof SimulatorRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events/conversations': typeof ApiEventsConversationsRoute
  '/api/events/positions': typeof ApiEventsPositionsRoute
  '/api/events/trades': typeof ApiEventsTradesRoute
  '/api/events/trading': typeof ApiEventsTradingRoute
  '/api/events/workflow': typeof ApiEventsWorkflowRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sim/order': typeof ApiSimOrderRoute
  '/api/sim/stream': typeof ApiSimStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/simulator': typeof SimulatorRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events/conversations': typeof ApiEventsConversationsRoute
  '/api/events/positions': typeof ApiEventsPositionsRoute
  '/api/events/trades': typeof ApiEventsTradesRoute
  '/api/events/trading': typeof ApiEventsTradingRoute
  '/api/events/workflow': typeof ApiEventsWorkflowRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sim/order': typeof ApiSimOrderRoute
  '/api/sim/stream': typeof ApiSimStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/simulator'
    | '/api/$'
    | '/api/chat'
    | '/api/events/conversations'
    | '/api/events/positions'
    | '/api/events/trades'
    | '/api/events/trading'
    | '/api/events/workflow'
    | '/api/rpc/$'
    | '/api/sim/order'
    | '/api/sim/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/simulator'
    | '/api/$'
    | '/api/chat'
    | '/api/events/conversations'
    | '/api/events/positions'
    | '/api/events/trades'
    | '/api/events/trading'
    | '/api/events/workflow'
    | '/api/rpc/$'
    | '/api/sim/order'
    | '/api/sim/stream'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/simulator'
    | '/api/$'
    | '/api/chat'
    | '/api/events/conversations'
    | '/api/events/positions'
    | '/api/events/trades'
    | '/api/events/trading'
    | '/api/events/workflow'
    | '/api/rpc/$'
    | '/api/sim/order'
    | '/api/sim/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEventsConversationsRoute: typeof ApiEventsConversationsRoute
  ApiEventsPositionsRoute: typeof ApiEventsPositionsRoute
  ApiEventsTradesRoute: typeof ApiEventsTradesRoute
  ApiEventsTradingRoute: typeof ApiEventsTradingRoute
  ApiEventsWorkflowRoute: typeof ApiEventsWorkflowRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiSimOrderRoute: typeof ApiSimOrderRoute
  ApiSimStreamRoute: typeof ApiSimStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sim/stream': {
      id: '/api/sim/stream'
      path: '/api/sim/stream'
      fullPath: '/api/sim/stream'
      preLoaderRoute: typeof ApiSimStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sim/order': {
      id: '/api/sim/order'
      path: '/api/sim/order'
      fullPath: '/api/sim/order'
      preLoaderRoute: typeof ApiSimOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/workflow': {
      id: '/api/events/workflow'
      path: '/api/events/workflow'
      fullPath: '/api/events/workflow'
      preLoaderRoute: typeof ApiEventsWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/trading': {
      id: '/api/events/trading'
      path: '/api/events/trading'
      fullPath: '/api/events/trading'
      preLoaderRoute: typeof ApiEventsTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/trades': {
      id: '/api/events/trades'
      path: '/api/events/trades'
      fullPath: '/api/events/trades'
      preLoaderRoute: typeof ApiEventsTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/positions': {
      id: '/api/events/positions'
      path: '/api/events/positions'
      fullPath: '/api/events/positions'
      preLoaderRoute: typeof ApiEventsPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/conversations': {
      id: '/api/events/conversations'
      path: '/api/events/conversations'
      fullPath: '/api/events/conversations'
      preLoaderRoute: typeof ApiEventsConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  SimulatorRoute: SimulatorRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEventsConversationsRoute: ApiEventsConversationsRoute,
  ApiEventsPositionsRoute: ApiEventsPositionsRoute,
  ApiEventsTradesRoute: ApiEventsTradesRoute,
  ApiEventsTradingRoute: ApiEventsTradingRoute,
  ApiEventsWorkflowRoute: ApiEventsWorkflowRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiSimOrderRoute: ApiSimOrderRoute,
  ApiSimStreamRoute: ApiSimStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
